default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  allow_concurrency: true
development:
  <<: *default
  database: nico_chart_dev
  username: dev
  password: '321321'
  min_messages: warning
test:
  <<: *default
  database: nico_chart_test
  username: dev
  password: '321321'
  min_messages: error
